export default {
	total_count: 267,
	incomplete_results: false,
	items: [
		{
			url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/51",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-auto-class",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/51/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/51/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/51/events",
			html_url: "https://github.com/nathonius/obsidian-auto-class/issues/51",
			id: 2104102225,
			node_id: "I_kwDOGTMK0c59ag1R",
			number: 51,
			title: "How to set image size and multiple titles",
			user: {
				login: "AP2020C",
				id: 104355545,
				node_id: "U_kgDOBjhW2Q",
				avatar_url: "https://avatars.githubusercontent.com/u/104355545?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/AP2020C",
				html_url: "https://github.com/AP2020C",
				followers_url: "https://api.github.com/users/AP2020C/followers",
				following_url: "https://api.github.com/users/AP2020C/following{/other_user}",
				gists_url: "https://api.github.com/users/AP2020C/gists{/gist_id}",
				starred_url: "https://api.github.com/users/AP2020C/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/AP2020C/subscriptions",
				organizations_url: "https://api.github.com/users/AP2020C/orgs",
				repos_url: "https://api.github.com/users/AP2020C/repos",
				events_url: "https://api.github.com/users/AP2020C/events{/privacy}",
				received_events_url: "https://api.github.com/users/AP2020C/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 1,
			created_at: "2024-01-28T10:56:38Z",
			updated_at: "2024-01-28T17:05:44Z",
			closed_at: "2024-01-28T17:05:33Z",
			author_association: "NONE",
			active_lock_reason: null,
			body: 'Question 1:\r\nWhat rule should I enter to have the images at 40px, if they don\'t have a different size?\r\nThese codes did not work\r\nimg-max-width:40px;\r\nimg:not([style*="width"]) {    width: 40px !important;}\r\n--image-max-width:40px;\r\n--image-width:40px;\r\nimg-width:40px;\r\n--img-max-width:40px;\r\n\r\nQuestion 2:\r\nI used\r\n--h2-color: blue;\r\nand it works.\r\nHowever, I would have expected that\r\n--h*-color: blue;\r\nwould act on all titles. What syntax should I use?',
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/51/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/51/timeline",
			performed_via_github_app: null,
			state_reason: "completed",
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/55",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-trello",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/55/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/55/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/55/events",
			html_url: "https://github.com/nathonius/obsidian-trello/issues/55",
			id: 2101932104,
			node_id: "I_kwDOF5VBys59SPBI",
			number: 55,
			title: "New plugin name requirements",
			user: {
				login: "joethei",
				id: 7150512,
				node_id: "MDQ6VXNlcjcxNTA1MTI=",
				avatar_url: "https://avatars.githubusercontent.com/u/7150512?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/joethei",
				html_url: "https://github.com/joethei",
				followers_url: "https://api.github.com/users/joethei/followers",
				following_url: "https://api.github.com/users/joethei/following{/other_user}",
				gists_url: "https://api.github.com/users/joethei/gists{/gist_id}",
				starred_url: "https://api.github.com/users/joethei/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/joethei/subscriptions",
				organizations_url: "https://api.github.com/users/joethei/orgs",
				repos_url: "https://api.github.com/users/joethei/repos",
				events_url: "https://api.github.com/users/joethei/events{/privacy}",
				received_events_url: "https://api.github.com/users/joethei/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 0,
			created_at: "2024-01-26T10:04:39Z",
			updated_at: "2024-01-28T01:28:24Z",
			closed_at: "2024-01-28T01:28:24Z",
			author_association: "NONE",
			active_lock_reason: null,
			body: 'Hi @nathonius\n\nPer our [developer policies](https://docs.obsidian.md/Developer+policies),\nplease ensure that your plugin\'s name does not include the word "Obsidian".\nIn addition, the plugin name should not include the word "Plugin", as that is unecessary duplication.\nWe have already modified the name of your plugin to "Trello" in our records.\n\nTo maintain compliance, take the following actions:\n\n1. Modify the manifest.json file in your plugin repository.\n2. Generate a new release for your plugin to ensure users download the updated manifest.\n\nIf you have a idea for a different plugin name, you may also submit a pull request to the [obsidianmd/obsidian-releases](https://github.com/obsidianmd/obsidian-releases) repository.\n\nThank you for your cooperation.\n— the Obsidian team',
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/55/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/55/timeline",
			performed_via_github_app: null,
			state_reason: "completed",
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/5",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-github-link",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/5/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/5/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/5/events",
			html_url: "https://github.com/nathonius/obsidian-github-link/issues/5",
			id: 2097138199,
			node_id: "I_kwDOLAI_t858_8oX",
			number: 5,
			title: "Investigate using Nathonius instead of OfficerHalf",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "open",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 1,
			created_at: "2024-01-23T23:12:39Z",
			updated_at: "2024-01-29T16:58:05Z",
			closed_at: null,
			author_association: "OWNER",
			active_lock_reason: null,
			body: "This would likely mean updating other plugins as well",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/5/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/5/timeline",
			performed_via_github_app: null,
			state_reason: null,
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/4",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-github-link",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/4/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/4/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/4/events",
			html_url: "https://github.com/nathonius/obsidian-github-link/issues/4",
			id: 2097137858,
			node_id: "I_kwDOLAI_t858_8jC",
			number: 4,
			title: "Update plugin metadata with accurate description",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "open",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 0,
			created_at: "2024-01-23T23:12:13Z",
			updated_at: "2024-01-23T23:12:13Z",
			closed_at: null,
			author_association: "OWNER",
			active_lock_reason: null,
			body: null,
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/4/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/4/timeline",
			performed_via_github_app: null,
			state_reason: null,
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/3",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-github-link",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/3/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/3/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/3/events",
			html_url: "https://github.com/nathonius/obsidian-github-link/issues/3",
			id: 2097137269,
			node_id: "I_kwDOLAI_t858_8Z1",
			number: 3,
			title: "Create readme",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [
				{
					id: 6386117891,
					node_id: "LA_kwDOLAI_t88AAAABfKRtAw",
					url: "https://api.github.com/repos/nathonius/obsidian-github-link/labels/documentation",
					name: "documentation",
					color: "0075ca",
					default: true,
					description: "Improvements or additions to documentation",
				},
			],
			state: "open",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 0,
			created_at: "2024-01-23T23:11:29Z",
			updated_at: "2024-01-23T23:11:29Z",
			closed_at: null,
			author_association: "OWNER",
			active_lock_reason: null,
			body: "Replace the sample readme.md with actual content",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/3/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/3/timeline",
			performed_via_github_app: null,
			state_reason: null,
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/2",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-github-link",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/2/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/2/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/2/events",
			html_url: "https://github.com/nathonius/obsidian-github-link/issues/2",
			id: 2080544603,
			node_id: "I_kwDOLAI_t858Apdb",
			number: 2,
			title: "Test issue 2",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 0,
			created_at: "2024-01-14T01:45:21Z",
			updated_at: "2024-01-23T23:09:39Z",
			closed_at: "2024-01-23T23:09:39Z",
			author_association: "OWNER",
			active_lock_reason: null,
			body: null,
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/2/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/2/timeline",
			performed_via_github_app: null,
			state_reason: "completed",
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/1",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-github-link",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/1/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/1/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/1/events",
			html_url: "https://github.com/nathonius/obsidian-github-link/issues/1",
			id: 2080544234,
			node_id: "I_kwDOLAI_t858ApXq",
			number: 1,
			title: "Test issue",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 0,
			created_at: "2024-01-14T01:43:39Z",
			updated_at: "2024-01-23T23:09:39Z",
			closed_at: "2024-01-23T23:09:39Z",
			author_association: "OWNER",
			active_lock_reason: null,
			body: "How meta!",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/1/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-github-link/issues/1/timeline",
			performed_via_github_app: null,
			state_reason: "completed",
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-callout-collector/issues/1",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-callout-collector",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-callout-collector/issues/1/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-callout-collector/issues/1/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-callout-collector/issues/1/events",
			html_url: "https://github.com/nathonius/obsidian-callout-collector/issues/1",
			id: 1970525027,
			node_id: "I_kwDOJX-Px851c9Nj",
			number: 1,
			title: "Update Readme",
			user: {
				login: "siainbuletin",
				id: 97026492,
				node_id: "U_kgDOBciBvA",
				avatar_url: "https://avatars.githubusercontent.com/u/97026492?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/siainbuletin",
				html_url: "https://github.com/siainbuletin",
				followers_url: "https://api.github.com/users/siainbuletin/followers",
				following_url: "https://api.github.com/users/siainbuletin/following{/other_user}",
				gists_url: "https://api.github.com/users/siainbuletin/gists{/gist_id}",
				starred_url: "https://api.github.com/users/siainbuletin/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/siainbuletin/subscriptions",
				organizations_url: "https://api.github.com/users/siainbuletin/orgs",
				repos_url: "https://api.github.com/users/siainbuletin/repos",
				events_url: "https://api.github.com/users/siainbuletin/events{/privacy}",
				received_events_url: "https://api.github.com/users/siainbuletin/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "open",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 1,
			created_at: "2023-10-31T13:51:50Z",
			updated_at: "2023-10-31T14:34:19Z",
			closed_at: null,
			author_association: "NONE",
			active_lock_reason: null,
			body: "I got curious when I came across this plugin, but I'd love to know what it's actually about. Does it track callout block-IDs across the vault? What might be its use case?",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-callout-collector/issues/1/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-callout-collector/issues/1/timeline",
			performed_via_github_app: null,
			state_reason: null,
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/48",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-auto-class",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/48/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/48/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/48/events",
			html_url: "https://github.com/nathonius/obsidian-auto-class/issues/48",
			id: 1909989048,
			node_id: "I_kwDOGTMK0c5x2B64",
			number: 48,
			title: "Feature request: Add class(es) to pages based on some programmable logic",
			user: {
				login: "voltel",
				id: 17889468,
				node_id: "MDQ6VXNlcjE3ODg5NDY4",
				avatar_url: "https://avatars.githubusercontent.com/u/17889468?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/voltel",
				html_url: "https://github.com/voltel",
				followers_url: "https://api.github.com/users/voltel/followers",
				following_url: "https://api.github.com/users/voltel/following{/other_user}",
				gists_url: "https://api.github.com/users/voltel/gists{/gist_id}",
				starred_url: "https://api.github.com/users/voltel/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/voltel/subscriptions",
				organizations_url: "https://api.github.com/users/voltel/orgs",
				repos_url: "https://api.github.com/users/voltel/repos",
				events_url: "https://api.github.com/users/voltel/events{/privacy}",
				received_events_url: "https://api.github.com/users/voltel/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "open",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 0,
			created_at: "2023-09-23T20:18:42Z",
			updated_at: "2023-09-23T20:18:42Z",
			closed_at: null,
			author_association: "NONE",
			active_lock_reason: null,
			body: "I have a property on the page that denotes the expiration date. \r\nE.g., in the frontmatter properties YAML, it could look like this:\r\n```yaml\r\n---\r\nexpiration_date: 2023-11-01\r\n---\r\n```\r\nOr it could be in the body of the page as a Dataview metadata property: \r\n```md\r\n[Expiration date:: 2023-11-01]\r\n```\r\n\r\nI'd like pages that are viewed past the expiration date to have a special CSS applied.\r\n\r\nFor that, certain logic should be run for the page. \r\nAs **Dataview** works with properties and metadata on the page, it seems to be a choice to allow the user to configure a certain module which will export a callback function, which will be invoked with a current page in a parameter and Dataview global instance, if present. If this function returns True, the plugin will add the configured CSS classes to pages, or, if it returns a String or an array of Strings with CSS class names, will adds those. \r\n\r\nThis will allow having a more elaborate logic for marking pages with certain CSS classes. \r\n\r\n",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/48/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/48/timeline",
			performed_via_github_app: null,
			state_reason: null,
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/22",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/22/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/22/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/22/events",
			html_url: "https://github.com/nathonius/obsidian-jira-cloud/issues/22",
			id: 1848902587,
			node_id: "I_kwDOJ4Vmj85uNAO7",
			number: 22,
			title: "Evaluate the usefulness of this plugin compared to Obsidian Jira Issue",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [
				{
					id: 5704770152,
					node_id: "LA_kwDOJ4Vmj88AAAABVAfiaA",
					url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/labels/question",
					name: "question",
					color: "d876e3",
					default: true,
					description: "Further information is requested",
				},
			],
			state: "open",
			locked: false,
			assignee: null,
			assignees: [
				{
					login: "nathonius",
					id: 4851889,
					node_id: "MDQ6VXNlcjQ4NTE4ODk=",
					avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
					gravatar_id: "",
					url: "https://api.github.com/users/nathonius",
					html_url: "https://github.com/nathonius",
					followers_url: "https://api.github.com/users/nathonius/followers",
					following_url: "https://api.github.com/users/nathonius/following{/other_user}",
					gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
					starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
					subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
					organizations_url: "https://api.github.com/users/nathonius/orgs",
					repos_url: "https://api.github.com/users/nathonius/repos",
					events_url: "https://api.github.com/users/nathonius/events{/privacy}",
					received_events_url: "https://api.github.com/users/nathonius/received_events",
					type: "User",
					site_admin: false,
				},
			],
			milestone: null,
			comments: 3,
			created_at: "2023-08-14T02:54:10Z",
			updated_at: "2023-08-14T03:40:48Z",
			closed_at: null,
			author_association: "OWNER",
			active_lock_reason: null,
			body: "I done goofed, and this plugin kind of already existed; [Obsidian Jira Issue](https://marc0l92.github.io/obsidian-jira-issue/). Obviously it's not exactly the same, but it serves the same purpose.\r\n\r\nI should evaluate the differences between the two, figure out if I should deprecate this, or maybe contribute to that plugin. Or maybe they could be interoperable. That plugin already exposes a Jira api just like this one does, so any differences could probably be made up via templater or something.\r\n\r\n\r\n| Feature              | Cloud   | Issue   | Notes                                                                              |\r\n| -------------------- | ------- | ------- | ---------------------------------------------------------------------------------- |\r\n| Plugin API           | Yes     | Yes     | Obviously the scope of these differ.                                               |\r\n| Multiple Accounts    | Planned | Yes     | This one was already on the roadmap.                                               |\r\n| Jira Server          | No      | Yes     |                                                                                    |\r\n| Create Issue         | Yes     | No      | Jira Issue seems to be readonly.                                                   |\r\n| Inline issue view    | No      | Yes     | This is a super nice feature.                                                      |\r\n| Kanban support       | No      | Yes     |                                                                                    |\r\n| Multi-issue queries  | No      | Yes     |                                                                                    |\r\n| Dataview integration | Partial | Yes     | Only via metadata / templater.                                                     |\r\n| Paste link to issue  | Yes     | Unknown | This would be feasible via templater im sure.                                      |\r\n| Issue to metadata    | Yes     | Unknown | Honestly this isn't that useful though (especially with the release of properties) |\r\n| Issue links -> tags  | No      | Yes     | I'm not sure if this is automatic or triggered via command but it's a neat feature |\r\n",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/22/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/22/timeline",
			performed_via_github_app: null,
			state_reason: null,
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/19",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/19/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/19/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/19/events",
			html_url: "https://github.com/nathonius/obsidian-jira-cloud/issues/19",
			id: 1848287008,
			node_id: "I_kwDOJ4Vmj85uKp8g",
			number: 19,
			title: "create issues within obsidian",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [
				{
					id: 5704770105,
					node_id: "LA_kwDOJ4Vmj88AAAABVAfiOQ",
					url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/labels/enhancement",
					name: "enhancement",
					color: "a2eeef",
					default: true,
					description: "New feature or request",
				},
				{
					id: 5704770152,
					node_id: "LA_kwDOJ4Vmj88AAAABVAfiaA",
					url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/labels/question",
					name: "question",
					color: "d876e3",
					default: true,
					description: "Further information is requested",
				},
			],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 2,
			created_at: "2023-08-12T23:02:17Z",
			updated_at: "2023-08-14T02:44:38Z",
			closed_at: "2023-08-14T02:44:38Z",
			author_association: "OWNER",
			active_lock_reason: null,
			body: "Keep it simple. Should just be able to set the project, name, description. Should result in a link pasted in the current note.",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/19/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/19/timeline",
			performed_via_github_app: null,
			state_reason: "completed",
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-collapse-all/issues/41",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-collapse-all",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-collapse-all/issues/41/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-collapse-all/issues/41/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-collapse-all/issues/41/events",
			html_url: "https://github.com/nathonius/obsidian-collapse-all/issues/41",
			id: 1837958658,
			node_id: "I_kwDOFeNEts5tjQYC",
			number: 41,
			title: "What does the plugin do?",
			user: {
				login: "davidjroos",
				id: 15630844,
				node_id: "MDQ6VXNlcjE1NjMwODQ0",
				avatar_url: "https://avatars.githubusercontent.com/u/15630844?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/davidjroos",
				html_url: "https://github.com/davidjroos",
				followers_url: "https://api.github.com/users/davidjroos/followers",
				following_url: "https://api.github.com/users/davidjroos/following{/other_user}",
				gists_url: "https://api.github.com/users/davidjroos/gists{/gist_id}",
				starred_url: "https://api.github.com/users/davidjroos/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/davidjroos/subscriptions",
				organizations_url: "https://api.github.com/users/davidjroos/orgs",
				repos_url: "https://api.github.com/users/davidjroos/repos",
				events_url: "https://api.github.com/users/davidjroos/events{/privacy}",
				received_events_url: "https://api.github.com/users/davidjroos/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [
				{
					id: 2998346199,
					node_id: "MDU6TGFiZWwyOTk4MzQ2MTk5",
					url: "https://api.github.com/repos/nathonius/obsidian-collapse-all/labels/documentation",
					name: "documentation",
					color: "0075ca",
					default: true,
					description: "Improvements or additions to documentation",
				},
				{
					id: 4061287445,
					node_id: "LA_kwDOFeNEts7yElQV",
					url: "https://api.github.com/repos/nathonius/obsidian-collapse-all/labels/planned",
					name: "planned",
					color: "6FA927",
					default: false,
					description: "Planned for the next release",
				},
			],
			state: "open",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 2,
			created_at: "2023-08-05T22:20:27Z",
			updated_at: "2023-08-06T20:51:07Z",
			closed_at: null,
			author_association: "NONE",
			active_lock_reason: null,
			body: "Just saw your update on Discord but (like a lot of plugins!) I’m not entire sure what it does from the documentation.\r\n\r\nThis plug-in is probably/possibly useful to lots of people but they won’t know because the rocs don’t really describe the problem being solved.\r\n\r\nAt a minimum some screenshots of without/with plug-in would help!",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-collapse-all/issues/41/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-collapse-all/issues/41/timeline",
			performed_via_github_app: null,
			state_reason: null,
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/17",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/17/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/17/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/17/events",
			html_url: "https://github.com/nathonius/obsidian-jira-cloud/issues/17",
			id: 1833626422,
			node_id: "I_kwDOJ4Vmj85tSus2",
			number: 17,
			title: "search is just very inconsistent",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [
				{
					id: 5704770075,
					node_id: "LA_kwDOJ4Vmj88AAAABVAfiGw",
					url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/labels/bug",
					name: "bug",
					color: "d73a4a",
					default: true,
					description: "Something isn't working",
				},
			],
			state: "open",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 0,
			created_at: "2023-08-02T17:34:32Z",
			updated_at: "2023-08-02T17:34:32Z",
			closed_at: null,
			author_association: "OWNER",
			active_lock_reason: null,
			body: "There's definitely something wrong on Jira's side of things, potentially some rate limiting happening? Or they try to be smart and don't return any results if the results haven't changed? Unsure.\r\n\r\nI can alleviate this by only replacing the suggestions if the length of the suggestions !== 0 and potentially adding a larger debounce",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/17/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/17/timeline",
			performed_via_github_app: null,
			state_reason: null,
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/14",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/14/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/14/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/14/events",
			html_url: "https://github.com/nathonius/obsidian-jira-cloud/issues/14",
			id: 1826709542,
			node_id: "I_kwDOJ4Vmj85s4WAm",
			number: 14,
			title: "store token in localStorage",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [
				{
					id: 5704770152,
					node_id: "LA_kwDOJ4Vmj88AAAABVAfiaA",
					url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/labels/question",
					name: "question",
					color: "d876e3",
					default: true,
					description: "Further information is requested",
				},
			],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 1,
			created_at: "2023-07-28T16:19:38Z",
			updated_at: "2023-08-14T02:46:46Z",
			closed_at: "2023-08-14T02:46:46Z",
			author_association: "OWNER",
			active_lock_reason: null,
			body: "For security it might be better but for portability it sucks. Still it might be worth it if people are worried about privacy.",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/14/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/14/timeline",
			performed_via_github_app: null,
			state_reason: "not_planned",
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/9",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/9/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/9/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/9/events",
			html_url: "https://github.com/nathonius/obsidian-jira-cloud/issues/9",
			id: 1825048040,
			node_id: "I_kwDOJ4Vmj85syAXo",
			number: 9,
			title: "Templater examples throw an error if you use esc to cancel the select modal",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "open",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 0,
			created_at: "2023-07-27T19:26:56Z",
			updated_at: "2023-07-27T19:26:56Z",
			closed_at: null,
			author_association: "OWNER",
			active_lock_reason: null,
			body: "They probably just need a conditional check in there.",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/9/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/9/timeline",
			performed_via_github_app: null,
			state_reason: null,
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/8",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/8/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/8/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/8/events",
			html_url: "https://github.com/nathonius/obsidian-jira-cloud/issues/8",
			id: 1820647698,
			node_id: "I_kwDOJ4Vmj85shOES",
			number: 8,
			title: "Link to generate api token should actually be a link",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [
				{
					id: 5704770075,
					node_id: "LA_kwDOJ4Vmj88AAAABVAfiGw",
					url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/labels/bug",
					name: "bug",
					color: "d73a4a",
					default: true,
					description: "Something isn't working",
				},
			],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 0,
			created_at: "2023-07-25T15:56:32Z",
			updated_at: "2023-08-13T03:14:29Z",
			closed_at: "2023-08-13T03:14:29Z",
			author_association: "OWNER",
			active_lock_reason: null,
			body: "It's currently not clickable or selectable.",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/8/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/8/timeline",
			performed_via_github_app: null,
			state_reason: "completed",
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/7",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/7/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/7/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/7/events",
			html_url: "https://github.com/nathonius/obsidian-jira-cloud/issues/7",
			id: 1820626440,
			node_id: "I_kwDOJ4Vmj85shI4I",
			number: 7,
			title: '"Jira Cloud requires configuration" notification appears on every restart',
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [
				{
					id: 5704770075,
					node_id: "LA_kwDOJ4Vmj88AAAABVAfiGw",
					url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/labels/bug",
					name: "bug",
					color: "d73a4a",
					default: true,
					description: "Something isn't working",
				},
			],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 1,
			created_at: "2023-07-25T15:44:03Z",
			updated_at: "2023-07-25T15:55:37Z",
			closed_at: "2023-07-25T15:55:37Z",
			author_association: "OWNER",
			active_lock_reason: null,
			body: null,
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/7/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/7/timeline",
			performed_via_github_app: null,
			state_reason: "completed",
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/5",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/5/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/5/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/5/events",
			html_url: "https://github.com/nathonius/obsidian-jira-cloud/issues/5",
			id: 1817456838,
			node_id: "I_kwDOJ4Vmj85sVDDG",
			number: 5,
			title: "Add button to settings to verify Jira connection",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [
				{
					id: 5704770105,
					node_id: "LA_kwDOJ4Vmj88AAAABVAfiOQ",
					url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/labels/enhancement",
					name: "enhancement",
					color: "a2eeef",
					default: true,
					description: "New feature or request",
				},
			],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 1,
			created_at: "2023-07-24T02:00:36Z",
			updated_at: "2023-08-02T04:12:13Z",
			closed_at: "2023-08-02T04:12:13Z",
			author_association: "OWNER",
			active_lock_reason: null,
			body: null,
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/5/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/5/timeline",
			performed_via_github_app: null,
			state_reason: "completed",
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/4",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/4/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/4/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/4/events",
			html_url: "https://github.com/nathonius/obsidian-jira-cloud/issues/4",
			id: 1812634259,
			node_id: "I_kwDOJ4Vmj85sCpqT",
			number: 4,
			title: "add to community registry",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [
				{
					login: "nathonius",
					id: 4851889,
					node_id: "MDQ6VXNlcjQ4NTE4ODk=",
					avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
					gravatar_id: "",
					url: "https://api.github.com/users/nathonius",
					html_url: "https://github.com/nathonius",
					followers_url: "https://api.github.com/users/nathonius/followers",
					following_url: "https://api.github.com/users/nathonius/following{/other_user}",
					gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
					starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
					subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
					organizations_url: "https://api.github.com/users/nathonius/orgs",
					repos_url: "https://api.github.com/users/nathonius/repos",
					events_url: "https://api.github.com/users/nathonius/events{/privacy}",
					received_events_url: "https://api.github.com/users/nathonius/received_events",
					type: "User",
					site_admin: false,
				},
			],
			milestone: null,
			comments: 1,
			created_at: "2023-07-19T19:52:08Z",
			updated_at: "2023-08-14T02:44:50Z",
			closed_at: "2023-08-14T02:44:50Z",
			author_association: "OWNER",
			active_lock_reason: null,
			body: "PR created at https://github.com/obsidianmd/obsidian-releases/pull/2147",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/4/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/4/timeline",
			performed_via_github_app: null,
			state_reason: "completed",
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/3",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/3/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/3/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/3/events",
			html_url: "https://github.com/nathonius/obsidian-jira-cloud/issues/3",
			id: 1810272648,
			node_id: "I_kwDOJ4Vmj85r5pGI",
			number: 3,
			title: "Issue key search is inconsistent",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [
				{
					id: 5704770075,
					node_id: "LA_kwDOJ4Vmj88AAAABVAfiGw",
					url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/labels/bug",
					name: "bug",
					color: "d73a4a",
					default: true,
					description: "Something isn't working",
				},
			],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 1,
			created_at: "2023-07-18T16:17:19Z",
			updated_at: "2023-08-02T04:12:40Z",
			closed_at: "2023-08-02T04:12:40Z",
			author_association: "OWNER",
			active_lock_reason: null,
			body: "Sometimes searching by key `AB-1234` works, and sometimes it doesn't. I'm not sure yet why it's inconsistent. It may be an issue in Jira.js. Needs investigation.",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/3/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-jira-cloud/issues/3/timeline",
			performed_via_github_app: null,
			state_reason: "completed",
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/47",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-auto-class",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/47/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/47/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/47/events",
			html_url: "https://github.com/nathonius/obsidian-auto-class/issues/47",
			id: 1669461780,
			node_id: "I_kwDOGTMK0c5jgfcU",
			number: 47,
			title: "Not working after restart if tab is not focused",
			user: {
				login: "axelson",
				id: 9973,
				node_id: "MDQ6VXNlcjk5NzM=",
				avatar_url: "https://avatars.githubusercontent.com/u/9973?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/axelson",
				html_url: "https://github.com/axelson",
				followers_url: "https://api.github.com/users/axelson/followers",
				following_url: "https://api.github.com/users/axelson/following{/other_user}",
				gists_url: "https://api.github.com/users/axelson/gists{/gist_id}",
				starred_url: "https://api.github.com/users/axelson/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/axelson/subscriptions",
				organizations_url: "https://api.github.com/users/axelson/orgs",
				repos_url: "https://api.github.com/users/axelson/repos",
				events_url: "https://api.github.com/users/axelson/events{/privacy}",
				received_events_url: "https://api.github.com/users/axelson/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "open",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 0,
			created_at: "2023-04-15T15:49:49Z",
			updated_at: "2023-04-15T15:49:49Z",
			closed_at: null,
			author_association: "NONE",
			active_lock_reason: null,
			body: "I'm using obsidian-auto-class and setting a css class based on the path that a file is in. Opening new notes works great and my css class is auto-applied. However if I restart Obsidian when I have multiple tabs open, then the css class is not applied to any tabs that are not focused on startup. So I have to close and reopen those notes to get the css class applied.",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/47/reactions",
				total_count: 1,
				"+1": 1,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/47/timeline",
			performed_via_github_app: null,
			state_reason: null,
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/50",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-trello",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/50/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/50/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/50/events",
			html_url: "https://github.com/nathonius/obsidian-trello/issues/50",
			id: 1661676331,
			node_id: "I_kwDOF5VBys5jCysr",
			number: 50,
			title: "proper workflow for handling tasks?",
			user: {
				login: "mwotton",
				id: 68482,
				node_id: "MDQ6VXNlcjY4NDgy",
				avatar_url: "https://avatars.githubusercontent.com/u/68482?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/mwotton",
				html_url: "https://github.com/mwotton",
				followers_url: "https://api.github.com/users/mwotton/followers",
				following_url: "https://api.github.com/users/mwotton/following{/other_user}",
				gists_url: "https://api.github.com/users/mwotton/gists{/gist_id}",
				starred_url: "https://api.github.com/users/mwotton/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/mwotton/subscriptions",
				organizations_url: "https://api.github.com/users/mwotton/orgs",
				repos_url: "https://api.github.com/users/mwotton/repos",
				events_url: "https://api.github.com/users/mwotton/events{/privacy}",
				received_events_url: "https://api.github.com/users/mwotton/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 2,
			created_at: "2023-04-11T02:35:24Z",
			updated_at: "2023-04-12T02:27:16Z",
			closed_at: "2023-04-12T02:27:15Z",
			author_association: "NONE",
			active_lock_reason: null,
			body: "first, thanks for the plugin - it's very useful already.\r\n\r\nI was wondering if you had a suggested workflow. I was expecting that I'd be able to bind a trello card to a task in obsidian, but i think the model here is more one trello card <=> one obsidian page?\r\n\r\nIdeally I'd like to be able to keep track of native tasks in obsidian and have it sync to trello , including archiving when the task is marked as finished. It's entirely possible my mental model is just wrong and I'm fighting the framework a bit.",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/50/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/50/timeline",
			performed_via_github_app: null,
			state_reason: "completed",
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/49",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-trello",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/49/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/49/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/49/events",
			html_url: "https://github.com/nathonius/obsidian-trello/issues/49",
			id: 1620519629,
			node_id: "I_kwDOF5VBys5glyrN",
			number: 49,
			title: "Hide Trello card ID",
			user: {
				login: "slim71",
				id: 39267642,
				node_id: "MDQ6VXNlcjM5MjY3NjQy",
				avatar_url: "https://avatars.githubusercontent.com/u/39267642?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/slim71",
				html_url: "https://github.com/slim71",
				followers_url: "https://api.github.com/users/slim71/followers",
				following_url: "https://api.github.com/users/slim71/following{/other_user}",
				gists_url: "https://api.github.com/users/slim71/gists{/gist_id}",
				starred_url: "https://api.github.com/users/slim71/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/slim71/subscriptions",
				organizations_url: "https://api.github.com/users/slim71/orgs",
				repos_url: "https://api.github.com/users/slim71/repos",
				events_url: "https://api.github.com/users/slim71/events{/privacy}",
				received_events_url: "https://api.github.com/users/slim71/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 5,
			created_at: "2023-03-12T21:33:49Z",
			updated_at: "2023-03-13T07:40:15Z",
			closed_at: "2023-03-12T22:24:45Z",
			author_association: "NONE",
			active_lock_reason: null,
			body: "I've noticed that when I attach a Trello card to a note, at the top of said note lies some kind of header like `trello_plugin_note_id: XXXX`.\r\nIs there any way to hide this from the note itself, _in reading mode_? I'd prefer to only look at the Trello card from the dedicated side panel...\r\n![image](https://user-images.githubusercontent.com/39267642/224574968-61dd9c22-d10e-4cfa-a6c6-1f36c045430a.png)\r\n",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/49/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/49/timeline",
			performed_via_github_app: null,
			state_reason: "completed",
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/46",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-auto-class",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/46/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/46/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/46/events",
			html_url: "https://github.com/nathonius/obsidian-auto-class/issues/46",
			id: 1610035509,
			node_id: "I_kwDOGTMK0c5f9zE1",
			number: 46,
			title: "Refactor to use preact for applicable views",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [
				{
					id: 3501455828,
					node_id: "LA_kwDOGTMK0c7Qs_nU",
					url: "https://api.github.com/repos/nathonius/obsidian-auto-class/labels/enhancement",
					name: "enhancement",
					color: "a2eeef",
					default: true,
					description: "New feature or request",
				},
			],
			state: "open",
			locked: false,
			assignee: null,
			assignees: [
				{
					login: "nathonius",
					id: 4851889,
					node_id: "MDQ6VXNlcjQ4NTE4ODk=",
					avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
					gravatar_id: "",
					url: "https://api.github.com/users/nathonius",
					html_url: "https://github.com/nathonius",
					followers_url: "https://api.github.com/users/nathonius/followers",
					following_url: "https://api.github.com/users/nathonius/following{/other_user}",
					gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
					starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
					subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
					organizations_url: "https://api.github.com/users/nathonius/orgs",
					repos_url: "https://api.github.com/users/nathonius/repos",
					events_url: "https://api.github.com/users/nathonius/events{/privacy}",
					received_events_url: "https://api.github.com/users/nathonius/received_events",
					type: "User",
					site_admin: false,
				},
			],
			milestone: null,
			comments: 1,
			created_at: "2023-03-05T03:09:43Z",
			updated_at: "2023-03-05T03:11:59Z",
			closed_at: null,
			author_association: "OWNER",
			active_lock_reason: null,
			body: null,
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/46/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/46/timeline",
			performed_via_github_app: null,
			state_reason: null,
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/42",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-auto-class",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/42/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/42/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/42/events",
			html_url: "https://github.com/nathonius/obsidian-auto-class/issues/42",
			id: 1590522965,
			node_id: "I_kwDOGTMK0c5ezXRV",
			number: 42,
			title: "Reevaluate scope setting",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [
				{
					id: 3501455835,
					node_id: "LA_kwDOGTMK0c7Qs_nb",
					url: "https://api.github.com/repos/nathonius/obsidian-auto-class/labels/question",
					name: "question",
					color: "d876e3",
					default: true,
					description: "Further information is requested",
				},
			],
			state: "open",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 0,
			created_at: "2023-02-19T01:24:04Z",
			updated_at: "2023-02-19T01:24:12Z",
			closed_at: null,
			author_association: "OWNER",
			active_lock_reason: null,
			body: "Currently, classes can be applied in read mode, edit mode, or both. However with the introduction of Live Preview mode, these lines are very blurred. Canvas throws this off even further. Need to reevaluate how and when css classes are applied.",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/42/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/42/timeline",
			performed_via_github_app: null,
			state_reason: null,
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/41",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-auto-class",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/41/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/41/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/41/events",
			html_url: "https://github.com/nathonius/obsidian-auto-class/issues/41",
			id: 1590521947,
			node_id: "I_kwDOGTMK0c5ezXBb",
			number: 41,
			title: "Allow applying classes via YAML frontmatter",
			user: {
				login: "nathonius",
				id: 4851889,
				node_id: "MDQ6VXNlcjQ4NTE4ODk=",
				avatar_url: "https://avatars.githubusercontent.com/u/4851889?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/nathonius",
				html_url: "https://github.com/nathonius",
				followers_url: "https://api.github.com/users/nathonius/followers",
				following_url: "https://api.github.com/users/nathonius/following{/other_user}",
				gists_url: "https://api.github.com/users/nathonius/gists{/gist_id}",
				starred_url: "https://api.github.com/users/nathonius/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/nathonius/subscriptions",
				organizations_url: "https://api.github.com/users/nathonius/orgs",
				repos_url: "https://api.github.com/users/nathonius/repos",
				events_url: "https://api.github.com/users/nathonius/events{/privacy}",
				received_events_url: "https://api.github.com/users/nathonius/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [
				{
					id: 3501455828,
					node_id: "LA_kwDOGTMK0c7Qs_nU",
					url: "https://api.github.com/repos/nathonius/obsidian-auto-class/labels/enhancement",
					name: "enhancement",
					color: "a2eeef",
					default: true,
					description: "New feature or request",
				},
			],
			state: "open",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 0,
			created_at: "2023-02-19T01:18:28Z",
			updated_at: "2023-02-19T01:25:14Z",
			closed_at: null,
			author_association: "OWNER",
			active_lock_reason: null,
			body: "#40 does this on a global level, but I think it would be better per-rule.",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/41/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/41/timeline",
			performed_via_github_app: null,
			state_reason: null,
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/48",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-trello",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/48/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/48/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/48/events",
			html_url: "https://github.com/nathonius/obsidian-trello/issues/48",
			id: 1571208708,
			node_id: "I_kwDOF5VBys5dpr4E",
			number: 48,
			title: "The obsidian rejected your token",
			user: {
				login: "LynnXie00",
				id: 30601091,
				node_id: "MDQ6VXNlcjMwNjAxMDkx",
				avatar_url: "https://avatars.githubusercontent.com/u/30601091?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/LynnXie00",
				html_url: "https://github.com/LynnXie00",
				followers_url: "https://api.github.com/users/LynnXie00/followers",
				following_url: "https://api.github.com/users/LynnXie00/following{/other_user}",
				gists_url: "https://api.github.com/users/LynnXie00/gists{/gist_id}",
				starred_url: "https://api.github.com/users/LynnXie00/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/LynnXie00/subscriptions",
				organizations_url: "https://api.github.com/users/LynnXie00/orgs",
				repos_url: "https://api.github.com/users/LynnXie00/repos",
				events_url: "https://api.github.com/users/LynnXie00/events{/privacy}",
				received_events_url: "https://api.github.com/users/LynnXie00/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 3,
			created_at: "2023-02-05T02:34:27Z",
			updated_at: "2023-07-15T15:35:35Z",
			closed_at: "2023-07-15T15:35:35Z",
			author_association: "NONE",
			active_lock_reason: null,
			body: 'My API token was newly created for this plugin, but when I connect, this plugin give an alert saying "the obsidian rejected your token."',
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/48/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/48/timeline",
			performed_via_github_app: null,
			state_reason: "completed",
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/37",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-auto-class",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/37/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/37/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/37/events",
			html_url: "https://github.com/nathonius/obsidian-auto-class/issues/37",
			id: 1561133228,
			node_id: "I_kwDOGTMK0c5dDQCs",
			number: 37,
			title: "Wildcard or Regex match",
			user: {
				login: "Rosefae",
				id: 4283381,
				node_id: "MDQ6VXNlcjQyODMzODE=",
				avatar_url: "https://avatars.githubusercontent.com/u/4283381?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/Rosefae",
				html_url: "https://github.com/Rosefae",
				followers_url: "https://api.github.com/users/Rosefae/followers",
				following_url: "https://api.github.com/users/Rosefae/following{/other_user}",
				gists_url: "https://api.github.com/users/Rosefae/gists{/gist_id}",
				starred_url: "https://api.github.com/users/Rosefae/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/Rosefae/subscriptions",
				organizations_url: "https://api.github.com/users/Rosefae/orgs",
				repos_url: "https://api.github.com/users/Rosefae/repos",
				events_url: "https://api.github.com/users/Rosefae/events{/privacy}",
				received_events_url: "https://api.github.com/users/Rosefae/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 1,
			created_at: "2023-01-29T05:28:06Z",
			updated_at: "2023-02-01T17:06:10Z",
			closed_at: "2023-02-01T16:54:53Z",
			author_association: "NONE",
			active_lock_reason: null,
			body: "Would it be possible to add the ability to use wildcard characters or regex in the path to target a collection of paths rather than just a specific one? Maybe a toggle in the settings to use `string.match()` instead of `string.startsWith()` when comparing the path, or preprocessing the entered path to handle globbing with asterisks or something.",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/37/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/37/timeline",
			performed_via_github_app: null,
			state_reason: "completed",
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/47",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-trello",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/47/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/47/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/47/events",
			html_url: "https://github.com/nathonius/obsidian-trello/issues/47",
			id: 1514599307,
			node_id: "I_kwDOF5VBys5aRvOL",
			number: 47,
			title: "Automatically suggest note name when connecting an obsidian Note to a new trello card",
			user: {
				login: "bdalia",
				id: 54666718,
				node_id: "MDQ6VXNlcjU0NjY2NzE4",
				avatar_url: "https://avatars.githubusercontent.com/u/54666718?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/bdalia",
				html_url: "https://github.com/bdalia",
				followers_url: "https://api.github.com/users/bdalia/followers",
				following_url: "https://api.github.com/users/bdalia/following{/other_user}",
				gists_url: "https://api.github.com/users/bdalia/gists{/gist_id}",
				starred_url: "https://api.github.com/users/bdalia/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/bdalia/subscriptions",
				organizations_url: "https://api.github.com/users/bdalia/orgs",
				repos_url: "https://api.github.com/users/bdalia/repos",
				events_url: "https://api.github.com/users/bdalia/events{/privacy}",
				received_events_url: "https://api.github.com/users/bdalia/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 1,
			created_at: "2022-12-30T15:36:44Z",
			updated_at: "2023-11-11T23:27:45Z",
			closed_at: "2023-11-11T23:27:45Z",
			author_association: "NONE",
			active_lock_reason: null,
			body: "It would be very useful if the plug-in will automatically suggest the Obsidian note name as the Trello card title when we are creating a new card.\r\n\r\nRegards",
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/47/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-trello/issues/47/timeline",
			performed_via_github_app: null,
			state_reason: "completed",
			score: 1,
		},
		{
			url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/36",
			repository_url: "https://api.github.com/repos/nathonius/obsidian-auto-class",
			labels_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/36/labels{/name}",
			comments_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/36/comments",
			events_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/36/events",
			html_url: "https://github.com/nathonius/obsidian-auto-class/issues/36",
			id: 1417225613,
			node_id: "I_kwDOGTMK0c5UeSWN",
			number: 36,
			title: "Can Auto Class activate a CSS class in the presence of any YAML metadata? (Banners plugin use case).",
			user: {
				login: "DryIce1",
				id: 59501376,
				node_id: "MDQ6VXNlcjU5NTAxMzc2",
				avatar_url: "https://avatars.githubusercontent.com/u/59501376?v=4",
				gravatar_id: "",
				url: "https://api.github.com/users/DryIce1",
				html_url: "https://github.com/DryIce1",
				followers_url: "https://api.github.com/users/DryIce1/followers",
				following_url: "https://api.github.com/users/DryIce1/following{/other_user}",
				gists_url: "https://api.github.com/users/DryIce1/gists{/gist_id}",
				starred_url: "https://api.github.com/users/DryIce1/starred{/owner}{/repo}",
				subscriptions_url: "https://api.github.com/users/DryIce1/subscriptions",
				organizations_url: "https://api.github.com/users/DryIce1/orgs",
				repos_url: "https://api.github.com/users/DryIce1/repos",
				events_url: "https://api.github.com/users/DryIce1/events{/privacy}",
				received_events_url: "https://api.github.com/users/DryIce1/received_events",
				type: "User",
				site_admin: false,
			},
			labels: [],
			state: "closed",
			locked: false,
			assignee: null,
			assignees: [],
			milestone: null,
			comments: 3,
			created_at: "2022-10-20T20:25:34Z",
			updated_at: "2023-02-19T01:44:41Z",
			closed_at: "2023-02-19T01:44:41Z",
			author_association: "NONE",
			active_lock_reason: null,
			body: 'Hi @OfficerHalf,\r\n\r\n**use case / Problem**\r\n- In v1 Obsidian using Inline Titles, the presence of a banner ([Banners Plugin](https://github.com/noatpad/obsidian-banners/)) usually covers the Inline Titles.\r\n- Therefore notes with a banner should have a [Banners Inline Title CSS snippet](https://github.com/noatpad/obsidian-banners/issues/76) automatically applied to adjust the inline title down.\r\n- However notes that have a banner don\'t universally share a unique file path or tag.\r\n- Can the "Banner Inline Title" CSS snippet be activated automatically by the Auto Class plugin in the presence of only the banner yaml? e.g. `banner: "https://picsum.photos/500"`\r\n\r\nthanks ',
			reactions: {
				url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/36/reactions",
				total_count: 0,
				"+1": 0,
				"-1": 0,
				laugh: 0,
				hooray: 0,
				confused: 0,
				heart: 0,
				rocket: 0,
				eyes: 0,
			},
			timeline_url: "https://api.github.com/repos/nathonius/obsidian-auto-class/issues/36/timeline",
			performed_via_github_app: null,
			state_reason: "completed",
			score: 1,
		},
	],
};
